In [18]:
import numpy as np
from numba import njit, types
import random
from datetime import datetime

### Environment definition

In [2]:
class Environment:

    def __init__(self):
        self.board = np.zeros((4, 4)).astype(np.uint16)
        i, j = self.random_choice()
        self.board[i][j] = Environment.generate_new()
        self.cul_reward = 0

    def random_choice(self):
        rows, cols = np.where(self.board == 0)
        if len(rows) == 0:
            return None, None
        idx = random.randint(0, len(rows) - 1)
        return rows[idx].item(), cols[idx].item()

    def apply_each_row_core(self, row_step, board):
        # print(row_step([4, 4, 0, 0]))
        new_rows = []
        total_rewards = 0
        for row in board:
            new_row, reward = row_step(row)
            new_rows.append(new_row)
            total_rewards += reward
        return np.array(new_rows), total_rewards

    def apply_to_each_row(self, row_step):
        return self.apply_each_row_core(row_step, self.board)

    def apply_to_each_col(self, col_step):
        new_board_T, total_rewards = self.apply_each_row_core(col_step, self.board.T)
        return new_board_T.T, total_rewards

    def generate_new():
        return 2 if random.random() < 0.9 else 4

    def reverse_squeeze(row):
        new_row, reward = squeeze(row[::-1])
        return new_row[::-1], reward

    def move_left(self):
        new_board, reward = self.apply_to_each_row(squeeze)
        self.board = new_board
        self.cul_reward += reward
        return new_board, reward
        # new_board = np.apply_along_axis(squeeze, axis=1, arr=self.board)
        

    def move_right(self):
        new_board, reward = self.apply_to_each_row(Environment.reverse_squeeze)
        self.board = new_board
        self.cul_reward += reward
        return new_board, reward
        
        # return np.apply_along_axis(reverse_squeeze, axis=1, arr=self.board)

    def move_up(self):
        # return np.apply_along_axis(squeeze, axis=0, arr=self.board)
        new_board, reward = self.apply_to_each_col(squeeze)
        self.board = new_board
        self.cul_reward += reward
        return new_board, reward

    def move_down(self):
        new_board, reward = self.apply_to_each_col(Environment.reverse_squeeze)
        self.board = new_board
        self.cul_reward += reward
        return new_board, reward
        # return np.apply_along_axis(reverse_squeeze, axis=0, arr=self.board)

    def step(self, action):
        old_board = self.board
        new_board, reward = None, None
        if action == 0:
            new_board, reward = self.move_left()
        elif action == 1:
            new_board, reward = self.move_right()
        elif action == 2:
            new_board, reward = self.move_up()
        elif action == 3:
            new_board, reward = self.move_down()
        else:
            print("wrong action")

        is_done = False
        if np.any(old_board != new_board):
            i, j = self.random_choice()
            self.board[i][j] = Environment.generate_new()
            is_done = self.check_done()
        
        # print(self.board, reward)
        return self.board, reward, is_done


    def check_done(self):
        if np.any(self.board == 0):
            # print("0")
            # print(self.board == 0)
            return False
        for i in range(4):
            for j in range(3):
                if self.board[i][j] == self.board[i][j + 1]:
                    # print("1", i, j)
                    return False
        for i in range(3):
            for j in range(4):
                if self.board[i][j] == self.board[i+1][j]:
                    # print("2", i, j)
                    return False
        return True

    def get_state(self):
        return torch.tensor(self.board.reshape(-1).astype(np.float32))


In [ ]:
env = Environment()
done = False
score = 0
while not done:
    action, exp_reward, pairs = get_max_action_and_rewards(env.board, 0, 3)
    print(action)
    new_board, reward, done = env.step(action)
    score += reward
    print(new_board)

In [10]:
print(datetime.now())
r = get_max_action_and_rewards(env.board, 0, 3)
print(datetime.now())

2026-02-17 08:40:06.298537
2026-02-17 08:40:07.892965


### Search movement operation definition

In [19]:
@njit
def random_choice(board):
    rows, cols = np.where(board == 0)
    if len(rows) == 0:
        return None, None
    idx = random.randint(0, len(rows) - 1)
    return rows[idx].item(), cols[idx].item()


@njit
def squeeze(row):
    reward = 0.0
    if np.sum(row != 0) == 0:
        return row, reward
        
    new_row = np.zeros(4, dtype=row.dtype)
    set_idx = 0
    start = find_next_not_zero(row, 0)
    while start != -1 and start < len(row):
        next_idx = find_next_not_zero(row, start + 1)
        
        if next_idx == -1:
            break
        if row[start] == row[next_idx]:
            new_row[set_idx] = row[start] * 2
            reward += new_row[set_idx]
            start = find_next_not_zero(row, next_idx + 1)
            set_idx += 1
        else:
            new_row[set_idx] = row[start]
            start = find_next_not_zero(row, next_idx)
            set_idx += 1
    if start != -1 and start < len(row):
        new_row[set_idx] = row[start]
    return new_row, float(reward)


@njit
def find_next_not_zero(row, idx):
    if idx >= len(row):
        return -1
    if row[idx] != 0:
        return idx
    for i in range(idx + 1, len(row)):
        if row[i] != 0:
            return i
    return -1


@njit
def apply_each_row_core(row_step, board):
    # Pre-allocate a 2D array with the same shape and type as the input board
    new_board = np.zeros_like(board)
    total_rewards = 0.0
    
    # Iterate by index to avoid dynamically building Python lists
    for i in range(board.shape[0]):
        new_row, reward = row_step(board[i])
        new_board[i] = new_row
        total_rewards += reward
        
    return new_board, total_rewards


@njit
def apply_to_each_row(row_step, board):
    return apply_each_row_core(row_step, board)


@njit
def apply_to_each_col(col_step, board):
    new_board_T, total_rewards = apply_each_row_core(col_step, board.T)
    return new_board_T.T, total_rewards


def generate_new():
    return 2 if random.random() < 0.9 else 4


@njit
def reverse_squeeze(row):
    new_row, reward = squeeze(row[::-1])
    return new_row[::-1], reward


@njit
def move_left(board):
    new_board, reward = apply_to_each_row(squeeze, board)
    return new_board, reward
    

@njit
def move_right(board):
    new_board, reward = apply_to_each_row(reverse_squeeze, board)
    return new_board, reward


@njit
def move_up(board):
    new_board, reward = apply_to_each_col(squeeze, board)
    return new_board, reward


@njit
def move_down(board):
    new_board, reward = apply_to_each_col(reverse_squeeze, board)
    return new_board, reward


@njit
def step_forward(board, action):
    # 0 left, 1 right, 2 up, 3 down
    if action == 0:
        new_board, reward = move_left(board)
    elif action == 1:
        new_board, reward = move_right(board)
    elif action == 2:
        new_board, reward = move_up(board)
    elif action == 3:
        new_board, reward = move_down(board)
    else:
        print("wrong action")
        new_board, reward = None, 0
    return new_board, reward

In [20]:
# @njit
# def get_available_actions(board):
#     actions = [0, 1, 2, 3]
#     funcs = [move_left, move_right, move_up, move_down]
#     available_actions = []
#     for action, func in zip(actions, funcs):
#         new_board, _ = func(board)
#         if np.any(new_board != board):
#             available_actions.append(action)
#     return available_actions

@njit
def get_available_actions(board):
    available_actions = []
    if np.any(move_left(board)[0] != board):
        available_actions.append(0)
    if np.any(move_right(board)[0] != board):
        available_actions.append(1)
    if np.any(move_up(board)[0] != board):
        available_actions.append(2)
    if np.any(move_down(board)[0] != board):
        available_actions.append(3)
    return available_actions
        


@njit
def possible_gen(board, search_depth, total_depth):
    coords = np.argwhere(board == 0)
    if search_depth < 2:
        # get all possible tiles
        gens = [(coord, value, prob * (1 / len(coords))) for coord in coords for value, prob in [(2, 0.9), (4, 0.1)]]
    else:
        # only high possible tiles
        gens = [(coord, value, prob * (1 / len(coords))) for coord in coords for value, prob in [(2, 1)]]
    return gens


### Draft implementation

In [4]:
# # 1
# @njit
# def get_max_action_and_rewards(board, search_depth, total_depth):
#     if search_depth == total_depth:
#         return 0, 0.0, []
#     max_action, max_gain = 0, 0.0
#     action_gain_pairs = []
#     for action in available_actions(board):
#         new_board, r1 = step_forward(board, action)
#         r2 = get_expected_reward(new_board, search_depth, total_depth)
#         r_sum = r1 + r2
#         if r_sum > max_gain:
#             max_gain = r_sum
#             max_action = action
#         action_gain_pairs.append((action, r_sum))
#     return max_action, max_gain, action_gain_pairs


# @njit
# def get_expected_reward(board, search_depth, total_depth):
#     # evaluate the random gen
#     r_sum = 0
#     for (x, y), gen_tile, gen_prob in possible_gen(board, search_depth, total_depth):
#         old_value = board[x, y]
#         board[x, y] = gen_tile
#         action, future_gain, action_gain_pairs = get_max_action_and_rewards(board, search_depth + 1, total_depth)
#         board[x, y] = old_value
#         r_sum += gen_prob * future_gain
#     return r_sum

# def monotonic_score(board):
#     each_row_diff = np.diff(board, axis=1)
#     each_col_diff = np.diff(board, axis=0)
#     ascend_row = np.all(each_row_diff >= 0, axis=1) # size: [4]
#     descend_row = np.all(each_row_diff <= 0, axis=1)
    
#     ascend_col = np.all(each_col_diff >= 0, axis=0)
#     descend_col = np.all(each_col_diff <= 0, axis=0)

#     interleaving_row_score = max(
#         np.sum([ascend_row[0], ascend_row[2], descend_row[1], descend_row[3]]),
#         np.sum([descend_row[0], descend_row[2], ascend_row[1], ascend_row[3]])
#     )

#     interleaving_col_score = max(
#         np.sum([ascend_col[0], ascend_col[2], descend_col[1], descend_col[3]]),
#         np.sum([descend_col[0], descend_col[2], ascend_col[1], ascend_col[3]])
#     )
#     return interleaving_row_score, interleaving_col_score


### Heuristic

In [21]:
score_base = np.array([
        [2 ** 0,  2 ** 1,  2 ** 2,   2 ** 3],
        [2 ** 7,  2 ** 6,  2 ** 5,   2 ** 4],
        [2 ** 8,  2 ** 9,  2 ** 10,  2 ** 11],
        [2 ** 15, 2 ** 14, 2 ** 13,  2 ** 12]], dtype=np.int32)


@njit
def monotonic_score2(board):
    all_scores = []
    rt_board = board.copy()
    max_tile = np.max(board)
    # max_in = np.any([board[0, 0] == max_tile, board[0, 3] == max_tile, board[3, 0] == max_tile, board[3, 3] == max_tile])
    # max_out_penalty = 0 if max_in else -2**15 * 10
    max_out_penalty = 0
    no_empty = np.sum(rt_board == 0)
    rotate_times = 0
    for i in range(4):
        rt_score = np.sum(rt_board * score_base)
        tr_score = np.sum(rt_board.T * score_base)
        

        # tr_score = empty_tile_reward(tr_score, no_empty)
        # rt_score = empty_tile_reward(rt_score, no_empty)
        
        # rt_smoothness = smoothness_score(rt_board, (rotate_times, False))
        # tr_smoothness = smoothness_score(rt_board.T, (rotate_times, True))
        
        rt_board = np.rot90(rt_board)
        
        all_scores.extend([rt_score, tr_score])
        
    # print(all_scores)
    return max(all_scores) - max_out_penalty


# @njit
def empty_tile_reward(score, empty):
    penalty = (score / (16 - empty))
    return penalty


def smoothness_discount(board, transform):
    ob_board = board.copy()
    rotate_num, transpose = transform
    for i in range(rotate_num):
        ob_board = np.rot90(ob_board)
    if transpose:
        ob_board = ob_board.T
    a = ob_board

    flatten = np.concatenate([(row if i % 2 == 1 else row[::-1]) for i, row in enumerate(ob_board)][::-1])
    flatten_pow = np.log2(flatten[flatten != 0])
    flatten_pow_diff = np.absolute(np.diff(flatten_pow))
    max_change = max(flatten_pow_diff) if len(flatten_pow_diff) > 0 else 1
    smoothness_ratio = 2 ** max_change
    return smoothness_ratio

@njit 
def benchmark_move_left(board, times):
    for i in range(times):
        move_left(board)

In [118]:
monotonic_score2(ob_board)

77813536

In [83]:
ob_board_2 = np.array([
    [4, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]
])
flatten = smoothness_score(ob_board, (2, False))
flatten

[11.  9.  8.  2.  6.  5.  6.  4.  2.  4.  3.  1.  1.  2.]


6.0

In [55]:
2 ** 15

32768

In [26]:
flatten = smoothness_score(ob_board, (2, False))

In [31]:
flatten = flatten[flatten != 0]

In [32]:
flatten

array([2048,  512,  256,    4,   64,   32,   64,   16,    4,   16,    8,
          2,    2,    4])

In [36]:
flatten_pow = np.log2(flatten)

In [40]:
flatten_pow

array([11.,  9.,  8.,  2.,  6.,  5.,  6.,  4.,  2.,  4.,  3.,  1.,  1.,
        2.])

In [41]:
np.absolute(np.diff(flatten_pow))

array([2., 1., 6., 4., 1., 1., 2., 2., 2., 1., 2., 0., 1.])

In [19]:
2048 * (2 ** 15) / (2048 * (2 ** 6)

61440

In [10]:
smoothness_score(ob_board, (2, False))

[   2    2    4    0    4   16    8    0   64   32   64   16 2048  512
  256    4]


In [68]:
[row for i, row in enumerate(board)]

[array([   4,  256,  512, 2048]),
 array([64, 32, 64, 16]),
 array([ 0,  8, 16,  4]),
 array([2, 2, 4, 0])]

In [67]:
board[3], np.reverse

AttributeError: module 'numpy' has no attribute 'reverse'

In [143]:
from numba.typed import List

In [147]:
pair_type = types.Tuple((types.int64, types.float64))

# @njit
def get_max_action_and_rewards_new(board, search_depth, total_depth):
    actions = get_available_actions(board)
    empty_pairs = List.empty_list(pair_type)
    if len(actions) == 0:
        return 0, 0.0, empty_pairs
    if search_depth == total_depth:
        return 0, monotonic_score2(board), empty_pairs
    max_action, max_gain = 0, 0.0
    action_gain_pairs = List.empty_list(pair_type)
    for action in actions:
        new_board, _ = step_forward(board, action)
        r2 = get_expected_reward_new(new_board, search_depth, total_depth)
        r_sum = float(r2)
        if r_sum > max_gain:
            max_gain = r_sum
            max_action = action
        action_gain_pairs.append((action, r_sum))
    return max_action, max_gain, action_gain_pairs


# @njit
def get_expected_reward_new(board, search_depth, total_depth):
    # evaluate the random gen
    r_sum = 0.0
    for (x, y), gen_tile, gen_prob in possible_gen(board, search_depth, total_depth):

        old_value = board[x, y]
        board[x, y] = gen_tile
        action, future_gain, action_gain_pairs = get_max_action_and_rewards_new(board, search_depth + 1, total_depth)
        # if search_depth == 0:
        #     print((x, y), gen_tile, gen_prob, action_gain_pairs)
        board[x, y] = old_value
        r_sum += gen_prob * future_gain
    return r_sum

In [139]:
ob_board = np.array([
    [4, 256, 512, 2048],
    [64, 32, 64, 16],
    [0, 8, 16, 4],
    [2, 2, 4, 0]])

In [158]:
get_max_action_and_rewards_new(ob_board, 0, 3)
# get_available_actions(ob_board)
# possible_gen(ob_board, 0, 1)

(1,
 77813995.96481483,
 ListType[Tuple(int64, float64)]([(0, 77813397.19611111), (1, 77813995.96481483), (2, 77813893.78750001), (3, 74523268.995), ...]))

4

In [156]:
ob_board_1_down = move_down(ob_board)[0]
print(ob_board_1_down)
print(get_expected_reward_new(ob_board_1_down, 0, 3))
print(monotonic_score2(ob_board_1_down))

[[   0  256  512    0]
 [   4   32   64 2048]
 [  64    8   16   16]
 [   2    2    4    4]]
74523268.995
33925688


In [64]:
# gen on 0, 3
ob_board_1_down_gen = ob_board_1_down
ob_board_1_down_gen[0, 3] = 2
print(ob_board_1_down_gen)
print(get_max_action_and_rewards_new(ob_board_1_down_gen, 1, 4))
print("move_left")
ob_board_1_down_2_left = move_left(ob_board_1_down_gen)[0]
print(ob_board_1_down_2_left)
print(get_expected_reward_new(ob_board_1_down_2_left, 1, 4))

[[   0  256  512    2]
 [   4   32   64 2048]
 [  64    8   16   16]
 [   2    2    4    4]]
(0, 5428308.76544185, [(0, 5428308.76544185), (1, 4315124.496309524), (2, 3379857.780178571)])
move_left
[[ 256  512    2    0]
 [   4   32   64 2048]
 [  64    8   32    0]
 [   4    8    0    0]]
5428308.76544185


In [60]:
ob_board_1_down_gen = ob_board_1_down
ob_board_1_down_gen[0, 0] = 2
print(ob_board_1_down_gen)
print(get_max_action_and_rewards_new(ob_board_1_down_gen, 1, 3))
print("move_left")
ob_board_1_down_2_left = move_left(ob_board_1_down_gen)[0]
print(ob_board_1_down_2_left)
print(get_expected_reward_new(ob_board_1_down_2_left, 1, 3))

[[   2  256  512    0]
 [   4   32   64 2048]
 [  64    8   16   16]
 [   2    2    4    4]]
(0, 5789860.507692307, [(0, 5789860.507692307), (1, 4043266.42760989), (2, 4887993.715833333)])
move_left
[[   2  256  512    0]
 [   4   32   64 2048]
 [  64    8   32    0]
 [   4    8    0    0]]
5789860.507692307


In [ ]:
ob_board_1_down_2_left = move_left(ob_board_1_down)

In [22]:
0.45 * 5789860 + 0.05 * 6281094 + 0.45 * 5488810 + 0.05 * 5490702

5663991.3

In [59]:
ob_board_1_left = move_left(ob_board)[0]
print(ob_board_1_left)
print(get_expected_reward_new(ob_board_1_left, 0, 3))
print(monotonic_score2(ob_board_1_left))

[[   4  256  512 2048]
 [  64   32   64   16]
 [   8   16    4    0]
 [   4    4    0    0]]
(2, 3) 2 0.3 [(0, 5700730.484126984), (1, 5199950.519682539), (3, 3481013.128333333)]
(2, 3) 4 0.03333333333333333 [(0, 5985774.742307693), (1, 5985628.834615383), (3, 3563253.379761905)]
(3, 2) 2 0.3 [(0, 5572463.084676433), (1, 5187577.377777778), (3, 2745117.353333334)]
(3, 2) 4 0.03333333333333333 [(0, 5572463.37112332), (1, 5212280.9892063495), (2, 5558147.9523809515), (3, 3543245.186031746)]
(3, 3) 2 0.3 [(0, 5572463.084676433), (1, 5187577.377777778), (2, 5187598.66), (3, 3481013.128333333)]
(3, 3) 4 0.03333333333333333 [(0, 5572463.37112332), (1, 5212280.9892063495), (2, 5558146.21904762), (3, 3563253.379761905)]
5624720.378862433
5985684.615384615


In [101]:
get_max_action_and_rewards_new(env.board, 0, 3)

(0, 164618.97738704344, [(0, 164618.97738704344), (3, 164618.97738704344)])

In [167]:
len(path)

3471

In [163]:
env.board

array([[  2,   0,   0,   0],
       [  8,   2,   0,   2],
       [128,   8,   0,   0],
       [256,   8,   2,   0]], dtype=uint16)

In [168]:
# env = Environment()
# env.board = new_board
done = False
# score = 0
# path = []
while not done:
    action, exp_reward, pairs = get_max_action_and_rewards_new(env.board, 0, 3)
    print(action)
    new_board, reward, done = env.step(action)
    score += reward
    # path.append(new_board.copy())
    print(new_board)

1
[[   4 1024 2048 4096]
 [ 256  128   64    8]
 [   0    0    2    8]
 [   0    2    2    4]]
1
[[   4 1024 2048 4096]
 [ 256  128   64    8]
 [   0    0    2    8]
 [   2    0    4    4]]
1
[[   4 1024 2048 4096]
 [ 256  128   64    8]
 [   2    0    2    8]
 [   0    0    2    8]]
1
[[   4 1024 2048 4096]
 [ 256  128   64    8]
 [   0    0    4    8]
 [   2    0    2    8]]
1
[[   4 1024 2048 4096]
 [ 256  128   64    8]
 [   0    0    4    8]
 [   0    2    4    8]]
2
[[   4 1024 2048 4096]
 [ 256  128   64   16]
 [   4    2    8    8]
 [   0    0    0    0]]
1
[[   4 1024 2048 4096]
 [ 256  128   64   16]
 [   0    4    2   16]
 [   0    0    0    2]]
2
[[   4 1024 2048 4096]
 [ 256  128   64   32]
 [   0    4    2    2]
 [   0    0    0    2]]
1
[[   4 1024 2048 4096]
 [ 256  128   64   32]
 [   0    0    4    4]
 [   2    0    0    2]]
2
[[   4 1024 2048 4096]
 [ 256  128   64   32]
 [   2    2    4    4]
 [   0    0    0    2]]
1
[[   4 1024 2048 4096]
 [ 256  128   64   32]
 [

In [106]:
new_board

array([[ 0,  4,  0,  0],
       [ 0,  0,  0,  4],
       [ 0,  0,  8,  2],
       [64, 32,  8,  4]], dtype=uint16)

In [ ]:
[[   4  256  512 1024]
 [  32  128   64   16]
 [   8   32    8    4]
 [   2    8    2    2]]

[[  64  256  512 2048]
 [   8   32   16    4]
 [   8    0    0    0]
 [   2    0    0    2]]

In [61]:
# expr starts
board = np.array([
    [64, 256, 512, 2048],
    [8, 32, 16, 4],
    [8, 0, 0, 0],
    [2, 0, 0, 2]])

In [47]:
new_board.dtype

dtype('uint8')

In [38]:
board = np.array([
    [2, 4, 12, 7],
    [3, 5, 11, 8],
    [6, 7, 10, 0],
    [5, 8, 9, 11]])

In [7]:
board = np.array([
    [2, 4, 6, 8],
    [3, 5, 7, 9],
    [4, 4, 5, 6],
    [5, 6, 9, 2]])
get_max_action_and_rewards_new(board, 0, 2)

(0, 477962.28, [(0, 477962.28), (1, 0.0)])

In [39]:
get_max_action_and_rewards_new(board, 0, 2)

(1, 661432.8, [(1, 661432.8), (2, 498688.20000000007), (3, 621787.6)])

In [50]:
board = np.array([
    [1, 2, 2, 0],
    [0, 2, 2, 0],
    [4, 2, 2, 4],
    [4, 4, 4, 4]
])
board = np.array([
    [1, 4, 2, 4],
    [0, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

In [51]:
%time
get_max_action_and_rewards(board, 0, 4)

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 8.82 µs


(0, 3.48, [(0, 3.48), (2, 0.0), (3, 1.04)])

In [27]:
available_actions(board)

[0, 1]

In [17]:
funcs = [move_left, move_right, move_up, move_down]
funcs[0](board)

(array([[1, 4, 0, 0],
        [4, 0, 0, 0],
        [4, 4, 4, 0],
        [8, 8, 0, 0]]),
 28.0)

### BitBoard Version

#### 5.1 Map construction

In [244]:
mask = 0xF

def bit_value(board, bit_pos):
    shift = bit_pos * 4
    return (board >> shift) & mask

def is_bits_equal(board, pos1, pos2):
    return bit_value(board, pos1) == bit_value(board, pos2)

def clear_bits(board, pos):
    board &= ~(0xF << pos * 4)
    return board

def set_bits(board, pos, value):
    set_mask = value << pos * 4
    board |= set_mask
    return board

def merge_bits(board, merge_pos, next_pos, set_pos):
    new_value = bit_value(board, merge_pos) + 1
    board = clear_bits(board, set_pos)
    board = clear_bits(board, merge_pos)
    board = clear_bits(board, next_pos)
    board = set_bits(board, set_pos, new_value)
    return board

def display_bits(board):
    for i in range(4):
        print(f"{(board & (0xFFFF << i * 4 * 4)) >> (i * 4 * 4):019_b}")

def display_bits2(board):
    mask = 0xFFFF << 48
    
    for i in range(4):
        print(f"{(board & (mask >> i * 4 * 4)) >> (48 - i * 16):019_b}")

def print_row(row):
    print(f"{row:019_b}")


def bit_squeeze(board, bit_pos): # array of pos
    set_idx = 0
    merge_idx = 0 # the front element of the merge
    next_idx = 1 # the second element of the merge
    while True:

        while next_idx < 4 and bit_value(board, bit_pos[next_idx]) == 0:
            next_idx += 1
        # print(merge_idx, next_idx)
        if next_idx >= 4:
            break
            
        if bit_value(board, bit_pos[merge_idx]) == 0: # if merge_idx is empty, move next-idx-tile to merge-idx-tile and continue
            # print("b1")
            value = bit_value(board, bit_pos[next_idx])
            board = clear_bits(board, bit_pos[next_idx])
            board = set_bits(board, bit_pos[set_idx], value)
            # set_idx += 0
            # merge_idx = 
            next_idx += 1
        elif is_bits_equal(board, bit_pos[merge_idx], bit_pos[next_idx]):  # there is a merge
            # print("b2")
            
            board = merge_bits(board, bit_pos[merge_idx], bit_pos[next_idx], bit_pos[set_idx])
            set_idx += 1
            merge_idx = set_idx
            next_idx += 1
        else:
            # print("b3")
            if next_idx - merge_idx > 1:
                merge_idx += 1
                set_idx += 1
            else:
                merge_idx += 1
                next_idx += 1
                set_idx += 1
        # print("end", merge_idx, next_idx)
    return board

In [234]:
state_map = []
base = 0b0
for i in range(2 ** 16):
    merged = bit_squeeze(base, [3, 2, 1, 0])
    state_map.append(merged)
    base = base + 0b1

reverse_state_map = []
base = 0b0
for i in range(2 ** 16):
    merged = bit_squeeze(base, [0, 1, 2, 3])
    reverse_state_map.append(merged)
    base = base + 0b1

In [235]:
len(state_map), len(reverse_state_map)

(65536, 65536)

In [28]:
state_map = np.array(state_map, dtype=np.uint64)
reverse_state_map = np.array(reverse_state_map, dtype=np.uint64)

#### 5.2 action construction

In [55]:
# @njit('uint64(uint64)', inline='always')
def move_left(board):
    row4 = state_map[board & 0xFFFF]
    row3 = state_map[(board >> 16) & 0xFFFF]
    row2 = state_map[(board >> 16 * 2) & 0xFFFF]
    row1 = state_map[(board >> 16 * 3) & 0xFFFF]
    return row1 << 16 * 3 | row2 << 16 * 2 | row3 << 16 * 1 | row4 << 16 * 0

# @njit('uint64(uint64)', inline='always')
def move_right(board):
    row4 = reverse_state_map[board & 0xFFFF]
    row3 = reverse_state_map[(board >> 16) & 0xFFFF]
    row2 = reverse_state_map[(board >> 16 * 2) & 0xFFFF]
    row1 = reverse_state_map[(board >> 16 * 3) & 0xFFFF]
    return row1 << 16 * 3 | row2 << 16 * 2 | row3 << 16 * 1 | row4 << 16 * 0

# @njit('uint64(uint64)', inline='always')
def transpose(board):
    keep = board & 0xF0F0_0F0F_F0F0_0F0F
    swap_down = board & 0x0F0F_0000_0F0F_0000
    swap_up = board & 0x0000_F0F0_0000_F0F0
    swap_1 = keep | swap_down >> 12 | swap_up << 12

    keep = swap_1 & 0xFF00_FF00_00FF_00FF
    swap_down = swap_1 & 0x00FF_00FF_0000_0000
    swap_up = swap_1 & 0x0000_0000_FF00_FF00
    swap_2 = keep | swap_down >> 24 | swap_up << 24

    return swap_2

# @njit('uint64(uint64)', inline='always')
def move_up(board):
    return transpose(move_left(transpose(board)))

# @njit('uint64(uint64)', inline='always')
def move_down(board):
    return transpose(move_right(transpose(board)))

In [41]:
board = 0b1000_1111_0111_0001_1000_0001_0000_0000_0000_0000_0000_0001_1100_1100_1100_0001
display_bits2(board)
print()
display_bits2(move_down(board))

1000_1111_0111_0001
1000_0001_0000_0000
0000_0000_0000_0001
1100_1100_1100_0001

0000_1111_0111_0000
0000_0001_0000_0000
1001_0000_0000_0001
1100_1100_1100_0010


#### 5.3 environment construction

#### algorithm construction

In [ ]:
score_base = np.array([
        [2 ** 0,  2 ** 1,  2 ** 2,   2 ** 3],
        [2 ** 7,  2 ** 6,  2 ** 5,   2 ** 4],
        [2 ** 8,  2 ** 9,  2 ** 10,  2 ** 11],
        [2 ** 15, 2 ** 14, 2 ** 13,  2 ** 12]], dtype=np.int32)

In [62]:
score = np.array([[0, 1, 2, 3],
[7, 6, 5, 4],
[8, 9, 10, 11],
[15, 14, 13, 12]])
score

score_bits = 0x0
for i in range(4):
    for j in range(4):
        score_bits |= int(score[i,j]) << ((3 - i) * 4 + (3 - j)) * 4
print(bin(score_bits))

display_bits2(score_bits)

0b100100011011101100101010010001001101010111111111011011100
0000_0001_0010_0011
0111_0110_0101_0100
1000_1001_1010_1011
1111_1110_1101_1100


In [39]:
row1_map = []
row = 0b1000_0100_0010_0001
print(f"{(row >> 12) | ((row >> 8) & 0xF) << 4 | ((row >> 4) & 0xF) << 8 | (row & 0xF) << 12:019_b}")

print(f"{row << 16:39_b}")

print(f"{((row >> 12) | ((row >> 8) & 0xF) << 4 | ((row >> 4) & 0xF) << 8 | (row & 0xF) << 12) << 32:059_b}")

print(f"{row << 48:39_b}")

0001_0010_0100_1000
1000_0100_0010_0001_0000_0000_0000_0000
0001_0010_0100_1000_0000_0000_0000_0000_0000_0000_0000_0000
1000_0100_0010_0001_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000


In [198]:
# row1_map = []
# row2_map = []
# row3_map = []
# row4_map = []

# base = 0b0
# for i in range(2 ** 16):
#     row1 = base >> 12 | ((base >> 8) & 0xF) << 4 | ((base >> 4) & 0xF) << 8 | (base & 0xF) << 12
#     row2 = base << 16
#     row3 = (base >> 12 | ((base >> 8) & 0xF) << 4 | ((base >> 4) & 0xF) << 8 | (base & 0xF) << 12) << 32
#     row4 = base << 48
#     row1_map.append(row1)
#     row2_map.append(row2)
#     row3_map.append(row3)
#     row4_map.append(row4)
#     base = base + 0b1


In [186]:
row1_map = []
row2_map = []
row3_map = []
row4_map = []
score_pow = 3
base = 0b0
for i in range(2 ** 16):
    elem1 = base >> 12
    elem2 = base >> 8 & 0xF
    elem3 = base >> 4 & 0xF
    elem4 = base & 0xF

    
    row1 = score_pow ** 0 * elem1 + score_pow ** 1 * elem2 + score_pow ** 2 * elem3 + score_pow ** 3 * elem4
    row2 = score_pow ** 7 * elem1 + score_pow ** 6 * elem2 + score_pow ** 5 * elem3 + score_pow ** 4 * elem4
    row3 = score_pow ** 8 * elem1 + score_pow ** 9 * elem2 + score_pow ** 10 * elem3 + score_pow ** 11 * elem4
    row4 = score_pow ** 15 * elem1 + score_pow ** 14 * elem2 + score_pow ** 13 * elem3 + score_pow ** 12 * elem4
    row1_map.append(row1)
    row2_map.append(row2)
    row3_map.append(row3)
    row4_map.append(row4)
    base = base + 0b1

In [194]:


# 1. directly calculate
# 2. 1 -> flip horizontally
# 3. 1 -> flip vertically
# 4. 1 -> flip horizontally -> flip vertically
# 5, 6, 7, 8. 1 -> transpose -> do (1, 2, 3, 4)

# [0, 1, 2, 3]
# [4, 5, 6, 7]
# [8, 9, 10, 11]
# [12, 13, 14, 15]
board = 0x0123456789ABCDEF
display_bits2(board)
def flip_horizontal(board):
    col1 = board & 0xF000_F000_F000_F000
    col2 = board & 0x0F00_0F00_0F00_0F00
    col3 = board & 0x00F0_00F0_00F0_00F0
    col4 = board & 0x000F_000F_000F_000F
    return col1 >> 12 | col2 >> 4 | col3 << 4 | col4 << 12

def flip_vertically(board):
    row1 = board & 0xFFFF_0000_0000_0000
    row2 = board & 0x0000_FFFF_0000_0000
    row3 = board & 0x0000_0000_FFFF_0000
    row4 = board & 0x0000_0000_0000_FFFF
    return row4 << 48 | row3 << 16 | row2 >> 16 | row1 >> 48

def board_score(board):
    row1 = board >> 48
    row2 = board >> 32 & 0xFFFF
    row3 = board >> 16 & 0xFFFF
    row4 = board & 0xFFFF
    return row1_map[row1] + row2_map[row2] + row3_map[row3] + row4_map[row4]

def monotonic_score(board):
    board_t = transpose(board)
    boards = [board, flip_horizontal(board), flip_vertically(board), flip_horizontal(flip_vertically(board)), 
             board_t, flip_horizontal(board_t), flip_vertically(board_t), flip_horizontal(flip_vertically(board_t))]
    scores = [board_score(board) for board in boards]
    return max(scores)

0000_0001_0010_0011
0100_0101_0110_0111
1000_1001_1010_1011
1100_1101_1110_1111


In [257]:
def get_available_actions(board):
    actions = []
    new_boards = [move_left(board), move_right(board), move_up(board), move_down(board)]
    return [(i, new_board) for i, new_board in enumerate(new_boards) if new_board != board]

def get_max_action_scores(board, depth, max_depth):
    action_boards = get_available_actions(board)
    if len(action_boards) == 0:
        return -1, 0
    max_action = -1
    max_scores = 0
    for action, new_board in action_boards:
        score = get_expected_score(new_board, depth, max_depth)
        if score > max_scores:
            max_action = action
            max_scores = score
    return max_action, max_scores

def get_expected_score(board, depth, max_depth):
    if depth > max_depth:
        return monotonic_score(board)
    gens = possible_gen(board, depth, max_depth)
    total_scores = 0
    for prob, new_board in gens:
        max_action, max_scores = get_max_action_scores(new_board, depth + 1, max_depth)
        total_scores += max_scores * prob
    return total_scores


def possible_gen(board, depth, max_depth):
    occupy_sign = board | board >> 1 | board >> 2 | board >> 3 # if there is value in the tile, the lowest bit will be 1;
    occupy_sign = ~occupy_sign
    occupy_sign &= 0x1111_1111_1111_1111
    num_empty = occupy_sign.bit_count()
    gens = []
    base_prob = 1 / num_empty
    for i in range(num_empty):
        lowest_bit = occupy_sign & -occupy_sign # for example 0x0000_0010_0000_0000, get the lowest bit (only 1 bit1)
        for value, prob in ([(1, 0.9), (2, 0.1)] if depth <=2 else [(1, 1)]):
            new_tile = lowest_bit * value
            new_board = board | new_tile
            gens.append((prob * base_prob, new_board))
        occupy_sign &= occupy_sign - 1
    return gens


KeyboardInterrupt: 

In [249]:
board = 0x1011_1011_1011_1011

In [195]:
get_available_actions(board)

[(0, 1162849547160964352),
 (1, 81915158324776431),
 (2, 4693601178988101632),
 (3, 72793415470575)]

In [197]:
display_bits2(board)

0000_0001_0010_0011
0100_0101_0110_0111
1000_1001_1010_1011
1100_1101_1110_1111


In [150]:
print_row(board & 0xFFFF)

0011_0011_0011_0011


In [147]:
board & 0xFFFF

13107

In [148]:
len(state_map)

0

In [139]:
board = 0b0000_0010_0001_0001_0001_0001_0001_0001_0010_0010_0010_0010_0011_0011_0011_0011

In [143]:
display_bits2(board)

0000_0010_0001_0001
0001_0001_0001_0001
0010_0010_0010_0010
0011_0011_0011_0011


In [120]:
occupy_sign = board | board >> 1 | board >> 2 | board >> 3 # if there is value in the tile, the lowest bit will be 1;
occupy_sign = ~occupy_sign
occupy_sign &= 0x1111_1111_1111_1111
num_empty = occupy_sign.bit_count()

In [123]:
display_bits2(occupy_sign)

0001_0000_0000_0000
0000_0000_0000_0000
0000_0000_0000_0000
0000_0000_0000_0000


In [118]:
occupy_sign

76861433640456465

In [73]:
row = board & 0xFFFF
print_row(row)

1100_1101_1110_1111


In [74]:
print_row(row4_map[row])

1100_1101_1110_1111_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000


In [77]:
print_row(board_score(board))

1100_1101_1110_1111_1011_1010_1001_1100_0100_0101_0110_0111_0011_0010_0001_0000


In [36]:
39 + 16 + 4

59

In [37]:
16 * 3 + 11

59

In [25]:
print(f"{(row >> 12) + (((row >> 8) & 0xF) << 4):09_b}")

0001_0001


In [24]:
((row >> 8) & 0xF) << 4

16

In [21]:
(row >> 12)

1

In [54]:
int(score[i, j])

12

In [49]:
print(score_bits)

-3607459613338291696


In [ ]:
[15, 8, 7, 0]
[14, 9, 6, 1]
[13, 10, 5, 2]


In [42]:
board = 0b1000_1000_1001_1001_0110_0000_0010_0010_0000_0000_0001_0000_0001_0001_0010_0000
display_bits2(board)

1000_1000_1001_1001
0110_0000_0010_0010
0000_0000_0001_0000
0001_0001_0010_0000


#### env

In [258]:
import random

In [376]:
board = 0b0

def actual_gen(board):
    occupy_sign = board | board >> 1 | board >> 2 | board >> 3 # if there is value in the tile, the lowest bit will be 1;
    occupy_sign = ~occupy_sign
    occupy_sign &= 0x1111_1111_1111_1111
    num_empty = occupy_sign.bit_count()
    gens = []
    
    actual_tile = random.randint(0, num_empty - 1)
    for i in range(actual_tile):
        occupy_sign &= occupy_sign - 1
    lowest_bit = occupy_sign & -occupy_sign
    if random.random() <= 0.1:
        new_tile = lowest_bit * 2
    else:
        new_tile = lowest_bit * 1
    new_board = board | new_tile
    return new_board

board = actual_gen(0)
new_board = 0
while True:
    action, score = get_max_action_scores(board, 1, 3)
    if action == 0:
        new_board = move_left(board)
    elif action == 1:
        new_board = move_right(board)
    elif action == 2:
        new_board = move_up(board)
    elif action == 3:
        new_board = move_down(board)
    else:
        print("wrong action")
        break
    new_board = actual_gen(new_board)
    if board == new_board:
        print("end")
        break
    board = new_board
    display_bits2(new_board)
    print()

0001_0000_0000_0001
0000_0000_0000_0000
0000_0000_0000_0000
0000_0000_0000_0000

0010_0000_0000_0000
0000_0000_0000_0001
0000_0000_0000_0000
0000_0000_0000_0000

0000_0000_0000_0000
0000_0000_0000_0000
0000_0000_0010_0000
0010_0000_0000_0001

0000_0000_0000_0000
0000_0000_0000_0001
0010_0000_0000_0000
0010_0001_0000_0000

0011_0001_0000_0001
0000_0000_0000_0000
0000_0000_0000_0000
0010_0000_0000_0000

0001_0000_0000_0000
0000_0000_0000_0000
0011_0000_0000_0000
0010_0001_0000_0001

0001_0000_0000_0000
0000_0000_0000_0001
0011_0000_0000_0000
0010_0010_0000_0000

0000_0000_0000_0001
0000_0000_0000_0001
0001_0000_0000_0011
0000_0000_0000_0011

0000_0000_0000_0001
0000_0000_0000_0000
0000_0000_0000_0010
0001_0000_0000_0100

0000_0000_0000_0000
0000_0000_0000_0001
0000_0000_0000_0010
0001_0001_0000_0100

0000_0001_0000_0000
0000_0000_0000_0001
0000_0000_0000_0010
0000_0000_0010_0100

0000_0000_0000_0001
0000_0001_0000_0001
0000_0000_0000_0010
0000_0000_0010_0100

0000_0000_0000_0001
0000_000

KeyboardInterrupt: 

In [371]:
get_max_action_scores(board, 1, 3)

(-1, 0)

In [372]:
board

0

### Time / Performance Analysis

In [12]:
import bitboard
import time

In [9]:
bitboard.init_tables(state_map, reverse_state_map)

In [10]:
# 2. Load the tables into the C-extension ONCE
bitboard.init_tables(state_map, reverse_state_map)

# 3. Run the blazing fast functions!
board = 0x1122334455667788  # Example bitboard
new_board = bitboard.move_left(board)

print(f"Old: {hex(board)}")
print(f"New: {hex(new_board)}")

Old: 0x1122334455667788
New: 0x2300450067008900


In [37]:
# CPython version
board = 0b1000_1000_1001_1001_0110_0000_0010_0010_0000_0000_0001_0000_0001_0001_0010_0000
start_time = time.perf_counter()
for i in range(10_000_000):
    new_board = bitboard.move_left(board)
end_time = time.perf_counter()
elapsed = end_time - start_time

print(f"CPython version: {elapsed:.6f} seconds")

# CPython version - inside loop
board = 0b1000_1000_1001_1001_0110_0000_0010_0010_0000_0000_0001_0000_0001_0001_0010_0000
start_time = time.perf_counter()
bitboard.benchmark_move_left(board, 10_000_000)
end_time = time.perf_counter()
elapsed = end_time - start_time

print(f"CPython version: {elapsed:.6f} seconds")

CPython version: 0.473072 seconds
CPython version: 0.004118 seconds


In [32]:
# Python bitboard version
board = 0b1000_1000_1001_1001_0110_0000_0010_0010_0000_0000_0001_0000_0001_0001_0010_0000
start_time = time.perf_counter()
for i in range(10_000_000):
    move_left(board)
end_time = time.perf_counter()
elapsed = end_time - start_time 
print(f"Python bitboard version: {elapsed:.6f} seconds")

Python bitboard version: 4.136425 seconds


In [30]:
# Python njit bitboard version
board = 0b1000_1000_1001_1001_0110_0000_0010_0010_0000_0000_0001_0000_0001_0001_0010_0000
start_time = time.perf_counter()
for i in range(10_000_000):
    move_left(board)
end_time = time.perf_counter()
elapsed = end_time - start_time 

print(f"Python njit bitboard version: {elapsed:.6f} seconds")


@njit
def benchmark_move_left_python_bitboard(board, times):
    for i in range(times):
        move_left(board)


start_time = time.perf_counter()
benchmark_move_left_python_bitboard(board, 10_000_000)
end_time = time.perf_counter()
elapsed = end_time - start_time 

print(f"Python bitboard version: {elapsed:.6f} seconds")

Python njit bitboard version: 0.768103 seconds
Python bitboard version: 0.063085 seconds


In [23]:
# numpy array version
example_board = np.array([
    [256, 512, 512, 512],
    [64, 0, 16, 16],
    [0, 0, 2, 0],
    [2, 0, 4, 0]])

start_time = time.perf_counter()
for i in range(10_000_000):
    new_board = move_left(example_board)

end_time = time.perf_counter()
elapsed = end_time - start_time

print(f"numpy array version: {elapsed:.6f} seconds")

benchmark_move_left(example_board, 10_000_000)

end_time = time.perf_counter()
elapsed = end_time - start_time

print(f"numpy array version: {elapsed:.6f} seconds")

# print(new_board)

numpy array version: 5.036270 seconds
numpy array version: 1.874860 seconds
